{$DEFINE LANGPACK}
{$DEFINE LANGENGLISH}
const MsgExtraInfo = 'Extra information in output file';
      MsgFail = '* Fatal * ';
      MsgPE = '* I/O format * ';
      MsgOk = '* ok * ';
      MsgWA = '* Wrong Answer * ';
      MsgPC = '* Partial Solution * ';
      MsgNotInfOpened = 'Fatal Error: input not opened';
      MsgWATJ = '* Bad input * ';
      MsgStrange = '* Unexpected Thing * ';
      MsgMissingFile = 'Missing file';
      MsgAttemptingReadUnopened = 'Attempting to read non-opened file';
      MsgFileReadError = 'File Read Error';
      MsgUnexpectedEof = 'Unexpected EOF';
      MsgUnexpectedSymbol = 'Unexpected character';
      MsgInPosition = 'in position';
      MsgLongString = 'String too long';
      MsgInstead = 'Instead of';
      MsgExpectedInteger = 'expected integer';
      MsgExpectedReal = 'expected real';
      MsgExpectedLong = 'expected 32-bit integer';
      MsgExpected16bitInteger = 'Required 16-bit integer, got';
      MsgBadLimits = 'Attempting to read integer with bad limits';
      MsgBLFrom = 'from';
      MsgBLTo = 'to';
      MsgRequiredLimits = 'Required number within range';
      MsgRLFrom = 'from';
      MsgRLTo = 'to';
      MsgGot = 'got';
      MsgRequiredLF = 'Expected EOL in position';
      MsgRequiredPresence = 'Required presence';
      MsgLineN = 'line';
      MsgPosition = 'position';
      MsgUnexpectedNewLine = 'Unexpected EOF in position';
      MsgExpectedEOF = 'Expected EOF in position';
      MsgSyntax = 'Usage';

