{$DEFINE LANGPACK}
{$DEFINE LANGRUSSIAN}
const MsgExtraInfo = 'Лишняя информация в выходном файле';
      MsgFail = '* Облом * ';
      MsgPE = '* Формат в/в * ';
      MsgOk = '* ok * ';
      MsgWA = '* Неверный ответ * ';
      MsgPC = '* Частичное решение * ';
      MsgNotInfOpened = 'ВНИМАНИЕ!!! Фатальная ошибка: не открыт входной файл';
      MsgWATJ = '* Неверный ввод * ';
      MsgStrange = '* Неожиданный поворот * ';
      MsgMissingFile = 'Отсутствует файл';
      MsgAttemptingReadUnopened = 'Попытка чтения из неоткрытого файла';
      MsgFileReadError = 'Ошибка чтения файла';
      MsgUnexpectedEof = 'Неожиданный конец файла';
      MsgUnexpectedSymbol = 'Неожиданный символ';
      MsgInPosition = 'в позиции';
      MsgLongString = 'Слишком длинная строка';
      MsgInstead = 'Вместо';
      MsgExpectedInteger = 'ожидалось целое';
      MsgExpectedReal = 'ожидалось вещественное';
      MsgExpectedLong = 'ожидалось 32-битное целое';
      MsgExpected16bitInteger = 'Затребовано 16-битное целое, а получено';
      MsgBadLimits = 'Попытка прочитать число в заведомо недопустимых пределах';
      MsgBLFrom = 'от';
      MsgBLTo = 'до';
      MsgRequiredLimits = 'Требовалось число в пределах';
      MsgRLFrom = 'от';
      MsgRLTo = 'до';
      MsgGot = 'а получено';
      MsgRequiredLF = 'Ожидался перевод строки в позиции';
      MsgRequiredPresence = 'Требовалось наличие';
      MsgLineN = 'строка';
      MsgPosition = 'позиция';
      MsgUnexpectedNewLine = 'Неожиданный перевод строки в позиции';
      MsgExpectedEOF = 'Ожидался конец файла в позиции';
      MsgSyntax = 'Синтаксис';

